[package]
name = "makeup-comparator"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "scrapped_webs",
]

[[bin]]
name = "makeup-comparator"

[dependencies]
scrapped-webs = {path = "scrapped_webs"}

[dev-dependencies]
rusty-hook = "^0.11.2"