name: Generate Release Tag

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Determine version
        id: determine_version
        run: |
          YEAR=$(date +"%Y")
          MONTH=$(date +"%m")
          LAST_TAG=$(git describe --tags --abbrev=0)
          MAJOR=$(echo $LAST_TAG | cut -d '.' -f 1)
          MINOR=$(echo $LAST_TAG | cut -d '.' -f 2)
          if [ "$YEAR" != "$MAJOR" ] || [ "$MONTH" != "$MINOR" ]; then
            PATCH=0
          else
            PATCH=$(echo $LAST_TAG | cut -d '.' -f 3)
          fi
          ID=$(($PATCH + 1))
          echo "::set-output name=version::$YEAR.$MONTH.$ID"
      - name: Create Git tag
        if: github.event.pull_request.merged == true
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.determine_version.outputs.version }}
          name: Release ${{ steps.determine_version.outputs.version }}
          draft: false
          prerelease: false
